add(patterns/context): store and retrieve values from a context
ultimate-go-korean/translation pull request #36
Opened 2020-10-10 17:38 UTC by TangoEnSkai

- add the original note
- page 164 to 166
  - ref: file:///Users/m-hahn/Downloads/Hoanh%20An,%20The%20Ultimate%20Go%20Study%20Guide.pdf

fyi, entire text is hand-typped.

2020-10-10 21:45 UTC, kkweon requested changes
다음 내용이 기대되네요.

2020-10-10 21:45 UTC, kkweon commented on 164-173/164-173.md
> +---
이건 다른 챕터도 넣지 않았기 때문에 일관성을 위해 없애주는 게 좋을 것 같습니다.

```suggestion
```

2020-10-10 21:45 UTC, kkweon commented on 164-173/164-173.md
> +---
```suggestion
```

2020-10-10 21:45 UTC, kkweon commented on 164-173/164-173.md
> +        nmae: "Hoanh",
```suggestion
        name: "Hoanh", 
```

2020-10-10 21:45 UTC, kkweon commented on 164-173/164-173.md
> +---
```suggestion
```

2020-10-10 21:45 UTC, kkweon commented on 164-173/164-173.md
>  ### Patterns 164
```suggestion
### Patterns
```

2020-10-10 21:45 UTC, kkweon commented on 164-173/164-173.md
>  #### Context 164
```suggestion
#### Context
```

2020-10-10 21:45 UTC, kkweon commented on 164-173/164-173.md
>  ##### Store and retrieve values from a context 164
```suggestion
##### Store and retrieve values from a context
```

2020-10-11 03:48 UTC, TangoEnSkai commented
> 다음 내용이 기대되네요.

리뷰 감사합니다. 작업을 저녁 늦게 해서 커밋에 잘못된 링크를 걸어서 수정하고 리뷰 체크 하겠습니다.

2020-10-11 11:18 UTC, TangoEnSkai commented
resolved prettier issue by 482fdf4

2020-10-11 11:23 UTC, aeuveritas approved these changes
수고하셨습니다. :+1:

2020-10-12 05:11 UTC, kkweon approved these changes

2020-10-12 05:11 UTC, kkweon commented
수고 하셨습니다.

2020-10-12 05:11 UTC, merged