add(patterns/context): store and retrieve values form a context
ultimate-go-korean/translation pull request #52
Opened 2020-10-16 14:59 UTC by TangoEnSkai

- replace original text (in English) to Korean translation
- fix minor typo, and delete unnecessary comments

this is a part of task #50

2020-10-17 08:30 UTC, kkweon requested changes
고생하셨습니다.

2020-10-17 08:30 UTC, kkweon commented on 164-173/164-173.md
> +키는 타입 특정적이고(type specific), 동일한 타입의 값만 매치할 수 있다.
한글로 읽었을때 어색하네요. **type of specific** (특정한 타입) 이 **type specific** (타입 특정적)으로 어감이 살짝 바뀌기도 했구요.

여기서 중요한 키워드는 specific 보다는 타입이다 라는 것이기에 아래와 같거나 조금 덜 어색하게 적혀있으면 좋을 것 같습니다.

```suggestion
키는 하나의 타입이고, 동일한 타입의 값만 매치할 수 있다.
```

2020-10-17 08:30 UTC, kkweon commented on 164-173/164-173.md
> +`user` 타입에 대한 값 생성.
명렁문도 한글로는 완전한 문장으로 표현됩니다.

```suggestion
`user` 타입에 대한 값 생성한다.
```

2020-10-17 08:30 UTC, kkweon commented on 164-173/164-173.md
> +키를 해당 타입의 제로값과 함꼐 선언.
ditto

```suggestion
키를 해당 타입의 제로값과 함꼐 선언한다.
```

2020-10-17 08:30 UTC, kkweon commented on 164-173/164-173.md
> +`Value`는 우리에게 적절하고 맞는 타입(the corrected type)을 전달할 수 있게 해 주고 (이 경우에 `userKey` 타입의 `uk`),
```suggestion
`Value`는 올바른 타입(the corrected type)을 전달할 수 있게 해 주고 (이 경우에 `userKey` 타입의 `uk`),
```

2020-10-17 08:30 UTC, kkweon commented on 164-173/164-173.md
> +비록 키의 값이 `0` 이고, 우리가 이 함수 호출에 `0`을 전달한다고 해도
**and** 가 아니라 **but** 

**비록 ~이지만** 이 들어가야 어떤게 다른 점인지 더 잘 느껴지는 것 같습니다.

```suggestion
비록 키의 실제 값이 `0`이지만, 이 함수 호출에 `0`을 전달한다 해도
```

2020-10-17 08:30 UTC, kkweon commented on 164-173/164-173.md
> +사용자 정의의 키 타입을 정의 해 보자.
```suggestion
사용자 정의의 키 타입을 사용하자.
```

2020-10-17 08:30 UTC, kkweon commented on 164-173/164-173.md
> +이 방법을 통해서, 우리 혹은 이 타입에 대해서 인지하고 있는 사람만이 context에서 그 값을 꺼내 올 수 있다.
```suggestion
그러면 이 타입에 대해서 인지하고 있을 경우에만 context에서 그 값을 꺼내 올 수 있다.
```

2020-10-17 08:30 UTC, kkweon commented on 164-173/164-173.md
> +왜냐하면 만약, 다수의 일부 프로그램(multiple partial programs)이 값이 `0`인 것을 사용하고자 한다면,
```suggestion
만약, 여러 프로그램이 숫자 `0` 키값을 사용해 `user`를 추출한다면,
```

2020-10-17 08:30 UTC, kkweon commented on 164-173/164-173.md
> +이 타입이 context 외부에서 값을 저장하고 검색할 수 있는 것에 대한 추가적인 보호 수준을 확장해 준다.
```suggestion
이런 타입이 context에 값을 저장 및 추출할 수 있도록 추가적인 보호해준다.
```

2020-10-17 08:30 UTC, kkweon commented on 164-173/164-173.md
> +콜 스택으로 이를 전달할 수 있다면, 향후에 레거시 코드의 가독성과 유지관리에 훨씬 더 유리할 것이다.
```suggestion
구체적인 타입을 사용하지 않으면 매 호출 시 왜 이런 식인지 계속 확인하게 만들기 때문에 잘못된 것을 알 수 있다.
따라서, 구체적인 타입을 사용하는 것이 향후 레거시 코드의 가독성과 유지관리에 훨씬 더 유리할 것이다.
```

2020-10-17 10:57 UTC, aeuveritas reviewed
수고하셨습니다. :)

2020-10-17 10:57 UTC, aeuveritas commented on 164-173/164-173.md
> +context에 `user` 값의 포인터 그리고 `userKey` 타입의 제로값을 저장하라.
```suggestion
context에 `user` 값의 포인터 그리고 `userKey` 타입의 제로값을 저장하자.
```
개인적으로 '~하라`는 너무 강압적으로 느껴지고, `~하자`가 더 자연스럽지 않나 생각합니다.

2020-10-17 12:21 UTC, TangoEnSkai commented on 164-173/164-173.md
> +키는 타입 특정적이고(type specific), 동일한 타입의 값만 매치할 수 있다.
감사합니다. 이부분 고민을 좀 많이 했었습니다. 매끄럽게 적기가 쉽지 않았습니다. 
말씀하신 대로 키워드가 타입이라는데 촛점을 맞추면 더 매끄럽게 읽혀지는 것 같습니다!

2020-10-17 12:23 UTC, TangoEnSkai commented on 164-173/164-173.md
> +이 방법을 통해서, 우리 혹은 이 타입에 대해서 인지하고 있는 사람만이 context에서 그 값을 꺼내 올 수 있다.
아 국어 정말 어렵네요... 감사합니다! 훨씬 더 자연스럽고 좋습니다.

2020-10-17 12:25 UTC, TangoEnSkai commented on 164-173/164-173.md
> +`Value`는 우리에게 적절하고 맞는 타입(the corrected type)을 전달할 수 있게 해 주고 (이 경우에 `userKey` 타입의 `uk`),
less is more. 👍

2020-10-17 12:25 UTC, TangoEnSkai commented on 164-173/164-173.md
> +context에 `user` 값의 포인터 그리고 `userKey` 타입의 제로값을 저장하라.
공감합니다. 하자 라는게 더 부드럽고 자연스럽게 느껴지네요.
앞으로 명령문 어투는 하자 라는 식으로 권유하듯 적어보겠습니다.

2020-10-17 12:31 UTC, aeuveritas approved these changes

2020-10-17 22:56 UTC, nicewook reviewed
수고하셨습니다.

2020-10-17 22:56 UTC, nicewook commented on 164-173/164-173.md
> +`context` 패키지는 Go 에서 취소(cancellation)와 데드라인(deadline)에 대한 해답(answer)이다.
```suggestion
`context` 패키지는 취소(cancellation)와 데드라인(deadline)을 지원한다.
```

조금 더 과감하게 번역투가 아닌 의역을 해도 되는 부분 같으며 answer 까지는 설명을 넣지 않아도 되지 않을까 싶습니다.

2020-10-17 22:56 UTC, nicewook commented on 164-173/164-173.md
> +실제로 저장되는 것은 값 뿐만이 아니라 그 값에 연관된 타입도 포함한다.
```suggestion
context 에 값을 저장하면, 그 값의 타입도 저장된다.
```

조금 더 자연스럽지 않나 싶어 제안합니다

2020-10-17 22:56 UTC, nicewook commented on 164-173/164-173.md
> +우리가 찾는 값의 타입을 알고 있는 경우에만 해당하는 context 내에서 값을 추출해 낼 수 있다.
```suggestion
값을 추출하려면, context 안의 값의 타입을 알아야만 한다.
```

다듬어 보았습니다.

2020-10-17 22:56 UTC, nicewook commented on 164-173/164-173.md
> +`userKey` 타입과 같은 아이디어는 context 내부에 값을 저장하고 싶을 떄 상당히 중요하다.
```suggestion
`userKey` 타입과 같은 아이디어는 context에  값을 저장하는 경우, 생각보다 상당히 중요한 개념이다.
```

타입을 알아야만(= 일종의 열쇠) 값을 추출해낼 수 있다는 개념을 설명해주는 부분이라 그 느낌을 전달해보고 싶었습니다.

2020-10-17 22:56 UTC, nicewook commented on 164-173/164-173.md
> +`user` 타입에 대한 값 생성한다.
```suggestion
`user` 타입의 값을 생성한다.
```

다듬어보았습니다.

2020-10-17 22:56 UTC, nicewook commented on 164-173/164-173.md
> +키를 해당 타입의 제로값과 함꼐 선언한다.
```suggestion
키를 제로값으로 선언한다.
```

다듬어 보았습니다.  선언과 정의의 구분, 혼용이 미세하게 마음에 걸리기는 합니다. 
저자는 선언을 자주 쓰는데 이번 번역에서는 그냥 써도 될 것 같기는 합니다.

2020-10-17 22:56 UTC, nicewook commented on 164-173/164-173.md
> +인터페이스를 사용하고 있기 때문에, 저장된 값을 꺼내오기 위해 type assertion을 수행해야 한다.
```suggestion
`user` 포인터 타입인 값을 추출해보자. 
`Value`는 특정한 타입의 값을 전달하면(이 경우 `userKey` 타입의 `uk`), 빈 인터페이스 타입을 반환한다.

인터페이스에 저장된 값을 꺼내려면 타입 단언(type assertion)을 해줘야 한다.
```

다듬어 보았습니다.

2020-10-17 22:56 UTC, nicewook commented on 164-173/164-173.md
> +우리가 정의한 `userKey`타입 기반이 아니기 때문이다.
```suggestion
`0`은 정수 타입이지, 우리가 정의한 `userKey` 타입이 아니기 때문이다.
```

다듬어보았습니다.

2020-10-17 22:56 UTC, nicewook commented on 164-173/164-173.md
> +따라서, 구체적인 타입을 사용하는 것이 향후 레거시 코드의 가독성과 유지관리에 훨씬 더 유리할 것이다.
```suggestion
사용자가 정의한 타입의 키를 사용하자.
그러면 이 타입을 알아야만 context에서 값을 꺼낼 수 있다. 
만약, 여러 프로그램이 숫자 `0` 키값을 사용해 `user`를 추출한다면, 
모든 것이 엉망이 되어버릴 수 있다. 
사용자 정의 타입은 context에 값을 저장하고 추출할 때에 추가적인 보호를 해준다.
구체적인 타입을 사용하지 않으면 매 호출 시 왜 이런 식인지 계속 확인하게 만들기 때문에 잘못된 것을 알 수 있다.
따라서, 구체적인 타입을 사용하는 것이 향후 레거시 코드의 가독성과 유지관리에 훨씬 더 유리할 것이다.
```

이 부분은 깔끔하게 해석이 어렵네요. [재방문] 키워드를 두고 천천히 들여다보면 어떨까요?

2020-10-18 05:56 UTC, TangoEnSkai commented
@nicewook 리뷰 감사합니다 많이 배웁니다. 다시 정리 해 보도록 하겠습니다. 
원문이 이해는 되는데 저에게는 좀 깔끔하지가 않습니다.
어느정도 의역을 해야 하지 않을까 싶기도 하네요..

2020-10-18 06:46 UTC, kkweon approved these changes

2020-10-18 23:46 UTC, nicewook commented
큰 틀에서 원저자가 말하려는 의도만 해치지 않으면 의역을 해도 되겠다 싶습니다.

2020-10-29 13:40 UTC, TangoEnSkai commented on 164-173/164-173.md
> +`userKey` 타입과 같은 아이디어는 context 내부에 값을 저장하고 싶을 떄 상당히 중요하다.
감사합니다. 언어를 사용을 안하니 정말 이렇게 부드럽게 적는게 쉽지 않습니다. 많이 배웁니다.

2020-10-29 13:40 UTC, TangoEnSkai commented on 164-173/164-173.md
> +키를 해당 타입의 제로값과 함꼐 선언한다.
선언으로 해도 크게 문제 되지 않을 것 같습니다. 감사합니다!

2020-10-29 13:42 UTC, TangoEnSkai commented on 164-173/164-173.md
> +따라서, 구체적인 타입을 사용하는 것이 향후 레거시 코드의 가독성과 유지관리에 훨씬 더 유리할 것이다.
공감합니다. 나중에 전체 머지 한 후 제가 참여한 곳은 다시 한번 더 검토할 생각입니다. 
#50 에 부채로 남겨두고 나중에 재방문 하도록 합시다.

2020-10-29 13:48 UTC, merged