translate 107~111 pages
ultimate-go-korean/translation pull request #65
Opened 2020-10-22 06:38 UTC by snowmerak

custom은 사용자 정의로 일단 일괄 처리하였고
concrete는 앞의 내용에 구현 타입, 구현체 등으로 적절히 대체해 놓았습니다.

2020-10-23 03:12 UTC, kkweon reviewed
수고하셨습니다.

2020-10-23 03:12 UTC, kkweon commented on 101-114/101-114.md
> +BehaviorAsContext는 net 패키지가 반환할 지도 모르는 있는 인터페이스를 어떻게 확인하는 지 보여준다.
```suggestion
`BehaviorAsContext`는 `net` 패키지가 반환할 지도 모르는 있는 인터페이스를 어떻게 확인하는 지 보여준다.
```

2020-10-23 03:12 UTC, kkweon commented on 101-114/101-114.md
> +이 구현 타입은 해당 인터페이스를 구현하고 있는 error 인터페이스를 가지고 있다. 우리는 해당 인터페이스를 정의하고 이용할 수 있다.
```suggestion
이 구현 타입은 해당 인터페이스를 구현하고 있는 `error` 인터페이스를 가지고 있다. 우리는 해당 인터페이스를 정의하고 이용할 수 있다.
```

2020-10-23 03:12 UTC, kkweon commented on 101-114/101-114.md
> +Go의 암시적 형변환에 감사한다. 우리는 원하는 메서드나 기능을 가진 인터페이스를 구현함으로 디커플링 단계에서 유지보수할 수 있고 타입 단언을 이용하는 switch 문법에서 구현 타입 대신에 사용할 수 있다.
```suggestion
Go의 암시적 형변환 덕분에, 원하는 메서드나 기능을 가진 인터페이스를 구현함으로 디커플링 단계에서 유지보수할 수 있고 타입 단언을 이용하는 `switch` 문법에서 구현 타입 대신에 사용할 수 있다.
```

2020-10-23 03:12 UTC, kkweon commented on 101-114/101-114.md
> +customError는 그저 빈 구조체일 뿐이다.
```suggestion
`customError`는 빈 구조체이다.
```

2020-10-23 03:12 UTC, kkweon commented on 101-114/101-114.md
> +Error는 error 인터페이스를 구현한다.
```suggestion
`Error`는 `error` 인터페이스를 구현한다.
```

2020-10-23 03:12 UTC, kkweon commented on 101-114/101-114.md
> +fail 함수는 둘 다 nil 값을 반환한다.
```suggestion
`fail` 함수는 둘 다 `nil` 값을 반환한다.
```

2020-10-23 03:12 UTC, kkweon commented on 101-114/101-114.md
> +우리가 fail을 호출하면 nil 값을 반환할 것이다. 하지만 우리는 error 인터페이스로써 반환하고 싶지만 customError 타입의 nil 값을 가질 뿐이다. customError 타입은 그저 만들어진 것에 불과하다. 우리는 사용자 정의 타입을 직접 사용할 수는 없고 오직 func fail() ([]byte, error) 처럼만 사용할 수 있다.
```suggestion
우리가 `fail`을 호출하면 `nil` 값을 반환할 것이다. 하지만 `error` 인터페이스로써 반환하고 싶지만 `customError` 타입의 `nil` 값을 가질 뿐이다. `customError` 타입은 그저 만들어진 것에 불과하다. 우리는 사용자 정의 타입을 직접 사용할 수는 없고 오직 `func fail() ([]byte, error)` 처럼만 사용할 수 있다.
```

2020-10-23 11:41 UTC, snowmerak commented on 101-114/101-114.md
> +이 클라이언트는 하나의 연결성을 가진다.
구조체 멤버로 bufio.Reader를 가지고 있고 그로 인해 연결을 하고 있고, client 자체가 연결을 의미하는 것과는 거리가 있다고 생각하여 연결성을 가진다고 표현했습니다. 아니면 멤버로 가진 게 name과 bufio.Reader 뿐이라 단순 커넥션으로 봐도 되는 건가요?

2020-10-28 09:15 UTC, kkweon requested changes
주어 전부 없애주시는게 좋을 것 같습니다.

예를 들면 

> 우리는 디커플링(decoupling)의 레벨에서 우리의 코드를 유지보수할 수 있게 되었다.

2020-10-28 09:16 UTC, kkweon commented on 101-114/101-114.md
> +'client'는 하나의 연결성을 가진다.
```suggestion
`client`는 하나의 연결성을 가진다.
```

2020-10-28 09:23 UTC, snowmerak commented on 101-114/101-114.md
> +'client'는 하나의 연결성을 가진다.
주어 변경과 함께 바꾸었습니다.

2020-10-28 09:26 UTC, snowmerak commented
> 주어 전부 없애주시는게 좋을 것 같습니다.
> 
> 예를 들면
> 
> > 우리는 디커플링(decoupling)의 레벨에서 우리의 코드를 유지보수할 수 있게 되었다.

2020-10-28 09:27 UTC, kkweon approved these changes

2020-10-28 10:36 UTC, gmlwo530 approved these changes

2020-10-28 10:39 UTC, merged