101-107 초안
ultimate-go-korean/translation pull request #74
Opened 2020-11-01 13:12 UTC by 979156

아래 2가지 특이사항이 있습니다.
1. unexported를 노출되지 않았다고 표현했습니다.
2. 언마셜의 경우 한국어에 대응되는 것이 없어보여서 유지했습니다.

2020-11-01 13:18 UTC, 979156 commented
@snowmerak 로서 --> 로써 변경 검토 요청드립니다. [국립국어원 '로서/로써' 링크](https://korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=117764#:~:text='%EB%A1%9C%EC%84%9C'%EB%8A%94%20%EC%9E%90%EA%B2%A9%2C%20%EC%A7%80%EC%9C%84,%EA%B0%99%EC%9D%B4%20'%EB%AC%B4%EC%97%87%EC%9C%BC%EB%A1%9C%EC%8D%A8'%EA%B0%80%20')를 봤을 때, 컨텍스트로서의 기능(Behavior as context)를 예로 들면 '컨텍스트로써 기능한다'와 같이 사용되는것이 더 적절해 보입니다.

2020-11-01 13:38 UTC, snowmerak commented
> @snowmerak 로서 --> 로써 변경 검토 요청드립니다. [국립국어원 '로서/로써' 링크](https://korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=117764#:~:text='%EB%A1%9C%EC%84%9C'%EB%8A%94%20%EC%9E%90%EA%B2%A9%2C%20%EC%A7%80%EC%9C%84,%EA%B0%99%EC%9D%B4%20'%EB%AC%B4%EC%97%87%EC%9C%BC%EB%A1%9C%EC%8D%A8'%EA%B0%80%20')를 봤을 때, 컨텍스트로서의 기능(Behavior as context)를 예로 들면 '컨텍스트로써 기능한다'와 같이 사용되는것이 더 적절해 보입니다.

저는 제가 가진 as의 느낌이 A as B가 B와 동급의 A같은 느낌입니다. 그래서 같은 자격을 의미하는 ~로서로 작성하였습니다. 들어주신 예시 또한 컨텍스트처럼 기능한다라고 생각됩니다. 혹여 제가 0개국어라 이해가 안된 것일 수도 있으니 더 구체적인 예시가 있으면 적어주셨으면 합니다.

2020-11-01 14:44 UTC, 979156 commented
@snowmerak 영어 A as B 자체로 봤을때는 말씀하신부분이 정말 적절합니다. 말씀드린 맥락은 글 전체로 보면 A as B에서 A를 이용해서 B를 해결하는 모습들을 글 전체적으로 저자가 보여줬기 때문입니다. 그래서 도구라고 인식하고 큰 맥락에서 제안드렸습니다. 그런데 말씀을 듣고 여러번 읽고 생각해 보니, 로서/로써 보다도 'A as B' 시리즈를 아예 'A를 통한 B 처리'로 바꾸는것이 어떨까 합니다.

다루는 내용 자체가 A를 이용해서 B영어도 사실 내용상 'Context processing using ~'가 적절해 보입니다. Type이나 Behavior를 가지고 context를 처리하는 방법들을 보여주고 있구요. 컨텍스트가 한국말로 치환시에 문맥정도가 될텐데 예를 들어 '타입정의를 이용한 문맥'시에 소제목 구체성이 다소 떨어져 보입니다.

그래서 결론은.. 'A를 통한 B 처리'도 한 번 검토 부탁드립니다!

2020-11-03 23:48 UTC, nicewook reviewed
여기까지만 문장을 다듬어 보았습니다.
번역 내용 자체에는 문제를 찾을 수 없었고, 이렇게 다듬어보면 어떨까 싶은 부분들이 있었습니다.

2020-11-03 23:48 UTC, nicewook commented on 101-114/101-114.md
> +무결성은 중요하다. 무결성 만큼 중요한것은 없다. 에러 처리는 그러한 무결성의 일부이다. 우리가 매일 하는 일에서 큰 부분을 차지한다. 작성하고자 하는 코드 자체의 일부로 여겨져야 한다. 먼저, 언어에서 제공하는 기본 에러 타입 구현의 동작에 대해 살펴보고자 한다.
```suggestion
무결성은 중요하며 이보다 중요한 것은 없다. 에러 처리는 그러한 무결성의 한 부분이다. 개발자가 매일 챙겨야 하는 부분이며, 작성하는 코드의 일부로 생각해야 한다. 먼저, 언어에서 제공하는 기본 에러 타입 구현의 동작에 대해 살펴보자.
```
```suggestion
무결성은 중요하다. 무결성 만큼 중요한것은 없다. 에러 처리는 그러한 무결성의 일부이다. 우리가 매일 하는 일에서 큰 부분을 차지한다. 작성하고자 하는 코드 자체의 일부로 여겨져야 한다. 먼저, 언어에서 제공하는 기본 에러 타입 구현의 동작에 대해 살펴보고자 한다.
```

2020-11-03 23:48 UTC, nicewook commented on 101-114/101-114.md
> +이것은 언어 자체에 포함되어 있기 때문에 노출되지 않은(unexported) 타입처럼 보인다. Error 라는 문자열 한 개를 반환하는 한 개의 기능에만 접근이 가능하다. 에러 처리는 사용자 코드 테스팅시에 항상 에러 인터페이스를 이용하기 위해 디커플링 되어 있다.
```suggestion
이것은 언어 자체에 포함되어 있기에, 외부로 노출되지 않는 타입처럼 보인다. `Error` 라는 문자열 한 개를 반환하는 메서드 하나만 외부에서 접근이 가능하다. 에러 처리는 코드 테스트를 할 때에 항상 `errer` 인터페이스를 사용하기에 디커플링 되어 있다.
```
```suggestion
이것은 언어 자체에 포함되어 있기 때문에 노출되지 않은(unexported) 타입처럼 보인다. Error 라는 문자열 한 개를 반환하는 한 개의 기능에만 접근이 가능하다. 에러 처리는 사용자 코드 테스팅시에 항상 에러 인터페이스를 이용하기 위해 디커플링 되어 있다.
```

2020-11-03 23:48 UTC, nicewook commented on 101-114/101-114.md
> +Go는 에러를 단지 값으로만 취급한다. 인터페이스 디커플링을 통해 값을 평가하게 된다. 에러 처리를 디커플링 하는 것은 지속적인 변경이 코드 전반에 걸쳐 광범위한 영향을 야기하기 때문이다. 에러를 다룰 때 인터페이스를 최대한 이용하는 것이 중요하다.
```suggestion
Go에서 에러는 단지 값일 뿐이며, 인터페이스 디커플링을 통해 그 값을 평가한다. 에러 처리를 디커플링 하는 것은 지속적인 변경이 코드 전반에 걸쳐 광범위한 영향을 야기하기 때문이다. 에러를 다룰 때 인터페이스를 최대한 이용하는 것이 중요하다.
```
```suggestion
Go는 에러를 단지 값으로만 취급한다. 인터페이스 디커플링을 통해 값을 평가하게 된다. 에러 처리를 디커플링 하는 것은 지속적인 변경이 코드 전반에 걸쳐 광범위한 영향을 야기하기 때문이다. 에러를 다룰 때 인터페이스를 최대한 이용하는 것이 중요하다.
```

2020-11-03 23:48 UTC, nicewook commented on 101-114/101-114.md
> +이것은 에러 패키지로부터 제공되는 기본적이며 구체적인 타입이다. 타입은 노출되지 않으면서 노출되지 않은 필드를 가진다. 이 방법은 사용자의 에러 판정을 구조화 할 수 있는 충분한 컨텍스트를 제공한다.
```suggestion
`error` 패키지에 있는 구체적인 기본 타입이다. 타입도, 그 내부의 필드도 외부로 노출하지 않는다. 이 방법은 사용자의 에러 판정을 구조화 할 수 있는 충분한 컨텍스트를 제공한다.
```
```suggestion
이것은 에러 패키지로부터 제공되는 기본적이며 구체적인 타입이다. 타입은 노출되지 않으면서 노출되지 않은 필드를 가진다. 이 방법은 사용자의 에러 판정을 구조화 할 수 있는 충분한 컨텍스트를 제공한다.
```

2020-11-03 23:48 UTC, nicewook commented on 101-114/101-114.md
> +사용자들에게 에러 상황을 어떻게 다룰 지 의사결정할 수 있도록 호출 시 에러 처리에 대해 충분한 내용을 제공해야 한다.
```suggestion
호출 시 충분한 내용을 담아 에러 처리를 하여, 호출자가 에러 상황에 대해 의사결정을 할 수 있게 한다. 
```

2020-11-03 23:48 UTC, nicewook commented on 101-114/101-114.md
> +포인터를 매개변수로 받아 문자열을 반환한다. 사용자가 이 메소드를 호출하여 실패상황에 대한 정보를 지닌 문자열을 얻어낼 수 있다.
```suggestion
포인터 리시버를 이용하여 문자열을 반환한다. 사용자는 이 메소드를 호출하여 실패상황에 대한 문자열을 얻어낼 수 있다.
```
```suggestion
포인터를 매개변수로 받아 문자열을 반환한다. 사용자가 이 메소드를 호출하여 실패상황에 대한 정보를 지닌 문자열을 얻어낼 수 있다.
```

2020-11-03 23:55 UTC, nicewook commented
> 아래 2가지 특이사항이 있습니다.
> 
> 1. unexported를 노출되지 않았다고 표현했습니다.
> 2. 언마셜의 경우 한국어에 대응되는 것이 없어보여서 유지했습니다.

1. 외부로 노출하지 않는다 정도면 좋을 듯 합니다. 
2. 마셜과 마샬, 어느게 좋은지 모르겠습니다. 둘 다 골고루 쓰이는 것 같네요

2020-11-04 02:57 UTC, snowmerak commented
> @snowmerak 영어 A as B 자체로 봤을때는 말씀하신부분이 정말 적절합니다. 말씀드린 맥락은 글 전체로 보면 A as B에서 A를 이용해서 B를 해결하는 모습들을 글 전체적으로 저자가 보여줬기 때문입니다. 그래서 도구라고 인식하고 큰 맥락에서 제안드렸습니다. 그런데 말씀을 듣고 여러번 읽고 생각해 보니, 로서/로써 보다도 'A as B' 시리즈를 아예 'A를 통한 B 처리'로 바꾸는것이 어떨까 합니다.
> 
> 다루는 내용 자체가 A를 이용해서 B영어도 사실 내용상 'Context processing using ~'가 적절해 보입니다. Type이나 Behavior를 가지고 context를 처리하는 방법들을 보여주고 있구요. 컨텍스트가 한국말로 치환시에 문맥정도가 될텐데 예를 들어 '타입정의를 이용한 문맥'시에 소제목 구체성이 다소 떨어져 보입니다.
> 
> 그래서 결론은.. 'A를 통한 B 처리'도 한 번 검토 부탁드립니다!

조금 늦었습니다. 한 이틀 정도 생각해봤습니다. 충분히 매력적인 번역이고 직관적인 표현이라 생각합니다. 이 PR이 끝나고 제 부분을 다듬어서 다시 올릴 때 'A를 통한 B 처리'로 수정해서 PR 하도록 하겠습니다.

2020-11-05 07:50 UTC, kkweon requested changes
수고하셨습니다.

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +New는 주어진 문자열에서 에러 인터페이스를 반환한다. 사용자가 New를 호출하면, text로 넘어온 값을 포함하는 errorString 값이 생성된다. 해당 타입의 실체에 대한 주소를 반환하기 때문에, 사용자는 실제 에러 내용을 가리키는 \*errorString을 통해 에러 인터페이스 값을 얻을 수 있다. 에러 처리는 이와 같은 방식으로 디커플링될 수
```suggestion
`New`는 주어진 문자열에서 에러 인터페이스를 반환한다. 사용자가 `New`를 호출하면, text로 넘어온 값을 포함하는 `errorString` 값이 생성된다. 해당 타입의 실체에 대한 주소를 반환하기 때문에, 사용자는 실제 에러 내용을 가리키는 `errorString`을 통해 에러 인터페이스 값을 얻을 수 있다. 에러 처리는 이와 같은 방식으로 디커플링될 수 있다.
```

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +아래는 Go에서 에러를 다루는 전통적인 방식이다. webCall 함수를 호출하고 에러 인터페이스를 변수에 저장하는 예시를 관찰할 것이다.
```suggestion
아래는 Go에서 에러를 다루는 전통적인 방식이다. `webCall` 함수를 호출하고 에러 인터페이스를 변수에 저장하는 예시를 관찰할 것이다.
```

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +nil은 Go에서 특별한 값이다. "error != nil"은 타입에 대한 실질적 값이 에러 인터페이스에 들어있는가 확인함을 의미한다. 에러가 nil 값이 아니면 실질적인 값이 저장된 것이기 때문이다. 값이 있는 경우에는 에러를 마주한 것이다.
```suggestion
`nil`은 Go에서 특별한 값이다. `error != nil` 은 타입에 대한 실질적 값이 에러 인터페이스에 들어있는가 확인함을 의미한다. 에러가 `nil` 값이 아니면 실질적인 값이 저장된 것이기 때문이다. 값이 있는 경우에는 에러를 마주한 것이다.
```

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +웹 요청을 처리하는 webCall 함수.
```suggestion
`webCall`은 웹 요청을 처리한다
```

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +요청에 문제가 있는 경우 ErrBadRequest 변수가 반환된다. 301/302가 반환되면 ErrBadRequest 변수가 반환된다.
```suggestion
요청에 문제가 있는 경우 `ErrBadRequest` 변수가 반환된다. 301/302가 반환되면 `ErrPageMoved` 변수가 반환된다.
```

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +웹 요청을 처리하는 webCall 함수.
```suggestion
`webCall`은 웹 요청을 처리한다
```

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +UnmarshalTypeError은 Go의 특정 타입으로 간주하기 어려운 JSON 값을 표현한다. 명명 규칙 : 타입 명명 시에는 접미사를 Error로 한다.
```suggestion
`UnmarshalTypeError`은 Go의 특정 타입으로 간주하기 어려운 JSON 값을 표현한다. 명명 규칙 : 타입 명명 시에는 접미사를 `Error`로 한다.
```

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +UnmarshalTypeError은 에러 인터페이스를 구현한다. 포인터 시맨틱(pointer semantics)을 이용한다. 구현 시, 모든 필드가 에러 메시지에서 사용되는가 검증한다. 이렇게 하지 않는다면, 문제가 발생할 것이다. 커스텀 에러 타입에 필드를 추가 해두어도 아래 메소드가 호출될 때 로그가 정상적으로 출력되지 않을 것이기 때문이다. 정말 필
```suggestion
`UnmarshalTypeError`은 에러 인터페이스를 구현한다. 포인터 시맨틱(pointer semantics)을 이용한다. 구현 시, 모든 필드가 에러 메시지에서 사용되는가 검증한다. 이렇게 하지 않는다면, 문제가 발생할 것이다. 커스텀 에러 타입에 필드를 추가 해두어도 아래 메소드가 호출될 때 로그가 정상적으로 출력되지 않을 것이기 때문이다. 정말 필요할 때만 이렇게 사용하기로 한다.
```

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +InvalidUnmarshalError는 Unmarshal 함수에 유효하지 않은 매개변수가 들어왔음을 알린다. Unmarshal의 매개변수로는 nil이 아닌 포인터가 들어와야 한다. 실제 타입은 Unmarshal 함수가 값에 대한 주소를 받지 않았을 때 반환값에 사용된다.
```suggestion
`InvalidUnmarshalError`는 `Unmarshal` 함수에 유효하지 않은 매개변수가 들어왔음을 알린다. `Unmarshal`의 매개변수로는 `nil`이 아닌 포인터가 들어와야 한다. 실제 타입은 `Unmarshal` 함수가 값에 대한 주소를 받지 않았을 때 반환값에 사용된다.
```

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +에러 인터페이스를 구현하는 InvalidUnmarshalError.
```suggestion
`InvalidUnmarshalError`은 에러 인터페이스를 구현한다.
```

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +Unmarshal 호출을 위해 사용하는 user 타입.
```suggestion
`Unmarshal` 호출을 위해 사용하는 `user` 타입.
```

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +Unmarshal 함수는 항상 실패할 언마셜을 실험한다. 매개변수 영역을 주목해보면, 첫 번째는 바이트 슬라이스이고, 두 번째는 빈 인터페이스이다. 빈 인터페이스는 기본적으로 어떤 것도 의미하지 않으며, 함수를 통해 어떤 값이든 받을 수 있다. 아래에서는 리플렉션을 이용해 인터페이스에 저장된 값의 실제 타입을 알아내고, 그것이 포인터가 아니거나 nil이
```suggestion
`Unmarshal` 함수는 항상 실패할 언마셜을 실험한다. 매개변수 영역을 주목해보면, 첫 번째는 바이트 슬라이스이고, 두 번째는 빈 인터페이스이다. 빈 인터페이스는 기본적으로 어떤 것도 의미하지 않으며, 함수를 통해 어떤 값이든 받을 수 있다. 아래에서는 리플렉션을 이용해 인터페이스에 저장된 값의 실제 타입을 알아내고, 그것이 포인터가 아니거나 `nil`이 아닌지 평가할 것이다. 결과에 기초하여 다른 에러 타입을 반환한다.
```

2020-11-05 07:50 UTC, kkweon commented on 101-114/101-114.md
> +컨텍스트 타입을 이용할 때의 결점이 한 가지 있다. 여기서는, 실제 값으로 돌아간다. 구체적인 타입들로 인해 코드에 결합성이 생기게 된다. json 패키지를 작성한 개발자가 구체적 타입들에 대해 변경하면, 예제 코드에도 연쇄적인 영향을 미치게 된다. 에러 인터페이스 디커플링에 의해 보호받지 못한다.
```suggestion
컨텍스트 타입을 이용할 때의 결점이 한 가지 있다. 여기서는, 실제 값으로 돌아간다. 구체적인 타입들로 인해 코드에 결합성이 생기게 된다. `json` 패키지를 작성한 개발자가 구체적 타입들에 대해 변경하면, 예제 코드에도 연쇄적인 영향을 미치게 된다. 에러 인터페이스 디커플링에 의해 보호받지 못한다.
```

2020-11-09 06:50 UTC, 979156 commented
> > @snowmerak 영어 A as B 자체로 봤을때는 말씀하신부분이 정말 적절합니다. 말씀드린 맥락은 글 전체로 보면 A as B에서 A를 이용해서 B를 해결하는 모습들을 글 전체적으로 저자가 보여줬기 때문입니다. 그래서 도구라고 인식하고 큰 맥락에서 제안드렸습니다. 그런데 말씀을 듣고 여러번 읽고 생각해 보니, 로서/로써 보다도 'A as B' 시리즈를 아예 'A를 통한 B 처리'로 바꾸는것이 어떨까 합니다.
> > 다루는 내용 자체가 A를 이용해서 B영어도 사실 내용상 'Context processing using ~'가 적절해 보입니다. Type이나 Behavior를 가지고 context를 처리하는 방법들을 보여주고 있구요. 컨텍스트가 한국말로 치환시에 문맥정도가 될텐데 예를 들어 '타입정의를 이용한 문맥'시에 소제목 구체성이 다소 떨어져 보입니다.
> > 그래서 결론은.. 'A를 통한 B 처리'도 한 번 검토 부탁드립니다!
> 
> 조금 늦었습니다. 한 이틀 정도 생각해봤습니다. 충분히 매력적인 번역이고 직관적인 표현이라 생각합니다. 이 PR이 끝나고 제 부분을 다듬어서 다시 올릴 때 'A를 통한 B 처리'로 수정해서 PR 하도록 하겠습니다.

@snowmerak 내용 확인이 늦었습니다. 리뷰 감사드립니다!

2020-11-09 06:51 UTC, 979156 commented on 101-114/101-114.md
> +컨텍스트 타입을 이용할 때의 결점이 한 가지 있다. 여기서는, 실제 값으로 돌아간다. 구체적인 타입들로 인해 코드에 결합성이 생기게 된다. json 패키지를 작성한 개발자가 구체적 타입들에 대해 변경하면, 예제 코드에도 연쇄적인 영향을 미치게 된다. 에러 인터페이스 디커플링에 의해 보호받지 못한다.
@kkweon 내용 확인이 늦었습니다. ``로 감싸는걸 일괄적으로 빼먹었었네요 ㅜㅜ 찾아주셔서 감사합니다!

2020-11-09 06:51 UTC, 979156 commented on 101-114/101-114.md
> +포인터를 매개변수로 받아 문자열을 반환한다. 사용자가 이 메소드를 호출하여 실패상황에 대한 정보를 지닌 문자열을 얻어낼 수 있다.
@nicewook 리뷰 확인이 늦었습니다 감사합니다! 반영했습니다!

2020-11-09 08:11 UTC, nicewook approved these changes
수고하셨습니다!

2020-11-17 06:20 UTC, snowmerak approved these changes
제가 리뷰어는 아니지만 오너 중 한명이고 오래동안 정체되어 있어서 어프로브하겠습니다.

2020-11-18 05:38 UTC, nicewook commented
두 분이 approve 하셔서 merge 하겠습니다

2020-11-18 05:38 UTC, merged