[eng->kor] 128-139 : part1
ultimate-go-korean/translation pull request #80
Opened 2020-11-06 15:18 UTC by baewang

### 개요
128-139 페이지 한글 번역했습니다.
길이가 애매해서 두 번으로 나누어서 번역예정입니다. 해당 부분은 part1입니다.

생각보다 한글로 번역하기 애매한 단어들이있어서 조금 애를 먹었네요.ㅠㅠㅠㅠ
data race 이런건 그냥 영어로 쓰는게 오히려 더 읽기 편한것 같기두하구,,,

리뷰 부탁드립니다 남겨주신 리뷰 바탕으로 part2도 적용해서 올리겠습니다 :)

2020-11-09 07:55 UTC, 979156 requested changes
번역하시느라 고생 많으셨습니다! 아래 내용 위주로 리뷰하였습니다. 검토 부탁드리겠습니다!
- 경어체 제거
- 7번째줄은 sync.WaitGroup을 이야기하고 싶어하는 것으로 느껴서 아래와 같이 제안드렸습니다.
- 10번째줄은 책 전체내용상 채널이 뒤에 나와서 그 전까지 뮤텍스를 쓰겠다 정도로 보여서 아래와 같이 제안드렸습니다.

감사합니다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +- WaitGroup이 Add, Done이나 Wait으로 끝나는 것 처럼 공유 자원에 대한 접근 상태를 동기화해줘야합니다.
WaitGroup을 Add와 Done, Wait으로 제어하는 것 처럼, 공유 자원에 대한 접근 상태를 동기화해야 한다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +- WaitGroup이 Add, Done이나 Wait으로 끝나는 것 처럼 공유 자원에 대한 접근 상태를 동기화해줘야합니다.
sync.WaitGroup 실제 제어시에 Add와 Done, Wait을 이용해서 제어하는 부분을 말하는 것으로 보여서 요런 느낌은 어떨까 합니다!

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +프로그램에 또다른 고루틴을 추가하게 되면 복잡도가 올라가게 됩니다. 우리는 고루틴을 무상태(stateless)로 실행하도록 둘 수 없기 때문에 조정이 필요하고, 멀티 스레드 환경에서 두 가지를 할 수 있습니다.
프로그램에 또 다른 고루틴을 추가하게 되면 복잡도가 올라가게 된다. 고루틴은 상태 없이(stateless)로 실행할 수 없기 때문에 제어가 필요하고, 멀티 스레드 소프트웨어를 작성할 때 두 가지의 선택지가 있다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +- 또는 고루틴들이 예측가능하고, 계획한대로 실행이 되도록 만들어줘야합니다.
또는 고루틴들을 예측 가능하고, 계획한 대로 실행이 되도록 만들 수도 있다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +값을 `counter`에 다시 저장해줍니다.
값을 `counter`에 다시 저장한다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +`counter`의 값을 늘려줍니다.
`counter`의 값을 늘린다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +다른 고루틴에게 쓰레드를 양보하고, 다시 대기열에 들어갑니다.
다른 고루틴에게 스레드를 양보하고, 다시 대기열에 들어간다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +고루틴이 끝날때까지 기다려줍니다.
고루틴이 끝날 때까지 기다린다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +이 때의 `counter`의 값을 저장해둡니다.
이 때의 `counter` 값을 저장해 둔다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +만약 우리가 `runtime.Goshed()`라는 줄을 추가하게되면, 다른 고루틴에게 CPU를 양보하게됩니다. 이때, 공유 자원을 읽게되면, 강제로 context switch가 일어나게되고, 자원 경쟁이 발생할 수 있습니다. 그렇게 되면 다시 돌아왔을 때 4라는 결과값을 얻지 못할수가 있습니다.
만약 우리가 `runtime.Goshed()`라는 코드를 추가하게 되면, 다른 고루틴에게 CPU를 양보하게 된다. 이때, 공유자원을 읽게 되면, 강제로 context switch가 일어나게되고, 자원 경쟁이 발생할 수 있다. 그렇게 되면 다시 돌아왔을 때 4라는 결과값을 얻지 못할 수도 있다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +2개의 고루틴을 만들어줍니다.
2개의 고루틴을 만든다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +`wg`는 동시성을 관리하는데 사용됩니다.
`wg`는 동시성을 관리하는데 사용한다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +여기서 발생하는 자원 경쟁: 주어진 시간동안 두개의 고루틴은 동시에 읽고, 쓸 수 있습니다. 그러나 우리는 운이 좋게도 각각의 고루틴이 3번의 실행을 모두 atomic하게 실행하고있다는 것을 볼 수 있습니다.
여기서 발생하는 자원 경쟁: 주어진 시간동안 두개의 고루틴은 동시에 읽고, 쓸 수 있다. 그러나 우리는 운이 좋게도 각각의 고루틴이 3번의 실행이 모두 atomic하다는 것을 볼 수 있다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +`counter`는 모든 고루틴으로부터 증가되는 변수입니다.
`counter`는 모든 고루틴에 의해 증가되는 변수이다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +채널을 사용하지 않아도, atomic function인 mutex를 사용하여 둘 다 수행할 수 있습니다. 채널은 우리에게 간단한 조정 방법을 제공하지만 대부분의 경우 mutex를 사용하고, 공유 자원에 대한 액세스 동기화를 사용하는 것이 가장 좋은 방법입니다.
채널을 사용하기 전 까지, 원자성을 보장하는 기능인 mutex를 사용하여 앞서 언급한 두 가지 선택지를 구현한다. 채널은 간단한 제어 방법을 제공하지만, 대부분의 경우 mutex를 사용하여 공유 자원에 대한 액세스 동기화를 사용하는 것이 가장 좋은 방법이다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +채널을 사용하지 않아도, atomic function인 mutex를 사용하여 둘 다 수행할 수 있습니다. 채널은 우리에게 간단한 조정 방법을 제공하지만 대부분의 경우 mutex를 사용하고, 공유 자원에 대한 액세스 동기화를 사용하는 것이 가장 좋은 방법입니다.
책 전체 문맥상 Data Race 다음 chapter가 Channel이어서 위와 같이 제시드렸습니다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +atomic 명령어는 Go에서 가장 빠른 방법입니다. Go는 메모리에서 한번에 4-8 바이트씩 동기화를 하기 때문입니다.
atomic 연산은 Go에서 가장 빠른 방법이다. Go는 메모리에서 한번에 4-8 바이트씩 동기화를 하기 때문이다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +Mutex는 그 다음으로 가장 빠릅니다. 채널은 매우 느린데, mutex일 뿐만 아니라 모든 데이터 구조와 로직이 함께 있기 때문입니다. 여러개의 고루틴이 같은 자원에 접근하려할 때 자원 경쟁이 발생합니다. 예를들어, 2개의 고루틴이 int 타입의 counter라는 변수에 같은 시각에 접근하길 원하는 상황을 예를 들어보겠습니다. 만약 실제로 같은 시간에
Mutex는 다음으로 빠르다. 채널은 매우 느린데, mutex일 뿐만 아니라 모든 데이터 구조와 로직이 함께 있기 때문이다. 여러개의 고루틴이 같은 자원에 접근하려할 때 자원 경쟁이 발생한다. 예를 들어, 2개의 고루틴이 int 타입의 counter라는 변수에 같은 시각에 접근하길 원하는 상황을 가정해 본다. 만약 실제로 같은 시간에 접근한다면  읽고 쓰기 위해 상호배제 할 것이다. 그렇기 때문에 공유하는 자원에 대해서 이런 접근이 필요할 때는 조정이 필요하다.

2020-11-09 07:55 UTC, 979156 commented on 128-139/128-139.md
> +진짜 문제는 이러한 자원 경쟁이 항상 랜덤하게 나타난다는 것입니다. 샘플 프로그램을 통해서 우리가 원하지 않는 자원 경쟁 상태를 만들어서 확인해보겠습니다.
진짜 문제는 이러한 자원 경쟁이 항상 예상치 못하게 나타난다는 것이다. 예시 프로그램을 통해, 우리가 원하지 않는 자원 경쟁 상태를 만들어서 확인한다.

2020-11-10 14:07 UTC, baewang commented
@979156 너무 꼼꼼하게 리뷰 해주셔서 쉽게 반영할 수 있었습니다ㅠㅠ 너무 감사합니다
리뷰 반영한내용 한번 확인 부탁드립니다 :)

2020-12-10 07:20 UTC, nicewook reviewed
수고하였습니다.

2020-12-10 07:20 UTC, nicewook commented on 128-139/128-139.md
> +프로그램에 또 다른 고루틴을 추가하게 되면 복잡도가 올라가게 된다. 고루틴은 상태 없이(stateless) 실행할 수 없기 때문에 제어가 필요하고, 멀티 스레드 소프트웨어를 작성할 때 두 가지의 선택지가 있다.
```suggestion
프로그램에 고루틴을 추가하면 복잡도가 엄청나게 올라간다. 고루틴을 언제나 상태없이(stateless) 실행할 수는 없기에 조율이 필요하다. 멀티 스레드 소프트웨어를 작성할 때는 사실상 두 가지 선택지가 있다.
```

2020-12-10 07:20 UTC, nicewook commented on 128-139/128-139.md
> +- 또는 고루틴들을 예측 가능하고, 계획한 대로 실행이 되도록 만들 수도 있다.
```suggestion
- WaitGroup에서 Add와 Done, Wait으로 제어하는 것 처럼, 공유 자원에 대한 접근 상태를 동기화하거나
- 고루틴을 예측 가능하고, 합리적으로 실행이 되도록 만들어야 한다. 
```

2020-12-10 07:20 UTC, nicewook commented on 128-139/128-139.md
> +채널을 사용하기 전 까지, 원자성을 보장하는 기능인 mutex를 사용하여 앞서 언급한 두 가지 선택지를 구현한다. 채널은 간단한 제어 방법을 제공하지만, 대부분의 경우 mutex를 사용하여 공유 자원에 대한 액세스 동기화를 사용하는 것이 가장 좋은 방법이다.
```suggestion
채널이 없었을 때는, 아토믹 함수나 mutex를 사용하여 앞서 언급한 두 가지 선택지를 구현하였다. 채널은 간단한 제어 방법을 제공하지만, 대부분의 경우는 아토믹 함수와 mutex를 사용하여 공유 자원에 대한 액세스 동기화를 사용하는 것이 가장 좋은 방법이다.
```

2020-12-17 02:04 UTC, merged

2020-12-17 02:04 UTC, nicewook commented
수고하셨습니다. 머지 하였습니다.