Add Translation 60-70
ultimate-go-korean/translation pull request #83
Opened 2020-11-17 15:30 UTC by Lee-KyungSeok

60-70 부분 번역 완료 했습니다.

2020-11-18 05:33 UTC, nicewook commented
오오~ 번역 완료하셨네요. 축하드립니다. ^^

2020-11-19 06:19 UTC, Lee-KyungSeok commented
> 오오~ 번역 완료하셨네요. 축하드립니다. ^^

감사합니다 ㅎㅎㅎ

2020-12-11 01:23 UTC, Ghun2 approved these changes
고생하셨습니다!

2020-12-13 09:43 UTC, 979156 requested changes
오타 외에는 번역자 분께서 고려해 보시고 고쳐주시면 좋을 것 같습니다! 늦어서 죄송스럽고 고생 많으셨습니다!

2020-12-13 09:43 UTC, 979156 commented on 55-70/55-70.md
> +- 새롭거나 유일한 것을 대표하는 타입을 선언한다. 가독성을 위해 별칭을 생성하지 않는다.
alias로 아시는 분들이 많을 것 같은데, 가독성을 위해 별칭(aliases)을 생성하지 않는다. 가 어떨까 제의드려봅니다!

2020-12-13 09:43 UTC, 979156 commented on 55-70/55-70.md
> +`Dog` 의 속성을 초기화해서 `Dog` 르 생성한다.
가벼운 오타가 있습니다!
`Dog` 의 속성을 초기화해서 `Dog` 를 생성한다.

2020-12-13 09:43 UTC, 979156 commented on 55-70/55-70.md
> +`Cat` 의 속성을 초기화해서 `Cat` 르 생성한다.
위와 동일한 오타로 보입니다! `Cat` 의 속성을 초기화해서 `Cat` 을 생성한다.

2020-12-13 09:43 UTC, 979156 commented on 55-70/55-70.md
> +여기까지는 괜찮을 지도 모른다. 하지만 이 코드는 컴파일되지 않는다. `Animals` 란 요소를 바탕으로 `Cat` 과 `Dog` 를 그루핑했기 때문이다. 즉, Go 는 서브타이핑 개념이 없는데도 불구하고 서브타이핑을 사용했다. Go 는 공통된 DNA를 바탕으로 그룹핑하는 것을 권장하지 않는다. 누구인지에만 초점을 맞춘다면 그룹화하는데 큰 제한이 있기
DNA에 필드라는 의역을 괄호형태로 달아주시면 처음 보시는 분들에게 조금 더 명시적이지 않을까 합니다!
Go는 공통된 DNA('구조체 내 공통된 필드'에 대한 비유)를 바탕으로 그룹핑하는 것을 권장하지 않는다.

2020-12-17 16:44 UTC, Lee-KyungSeok commented
> 오타 외에는 번역자 분께서 고려해 보시고 고쳐주시면 좋을 것 같습니다! 늦어서 죄송스럽고 고생 많으셨습니다!

저도 바빠서 이제야 고쳤네요 ㅜ.. 모두 반영 했습니다. 감사합니다!

2020-12-22 04:57 UTC, 979156 approved these changes
수고하셨습니다!

2020-12-22 04:57 UTC, merged