[eng->kor] 128-139 : part2 완료
ultimate-go-korean/translation pull request #99
Opened 2020-12-24 11:16 UTC by baewang

### 개요
128-139 페이지에 해당하는 부분의 남은 부분을 모두 번역하였습니다.
리뷰 부탁드립니다.

2020-12-26 00:01 UTC, 979156 commented on 128-139/128-139.md
> +`counter`에 안전하게 추가해줍니다. 주소를 첫번째 인자로 갖고, 얼마나 많은 고루틴이 있던지 상관없이 동기화 될 수 있는 아토믹 함수를 추가해라. 만약 우리가 같은 위치에서 여러개의 함수중 하나를 부른다면, 함수들은 직렬화된다. 이것은 직렬화하는 가장 빠른 방법이다.
`counter`에 동시성에 안전하게 1을 더해준다. 동기화 보장을 원하는 대상의 주소를 첫 번째 매개변수로 하는 원자적 연산 함수를 사용한다. 같은 주소에 대해 이러한 함수들을 사용하면, 이것들은 직렬화된다. 이것이 직렬화 할 수 있는 가장 빠른 방법이다.

어미 맞춤 + 약간의 의미 보강으로 요런 번역은 어떨까 합니다!

2020-12-26 00:09 UTC, 979156 commented on 128-139/128-139.md
> +이 호출은 이제 `AddInt64` 함수가 완료될 때까지 증가하기 때문에 관련이 없다.
이 호출은 `AddInt64` 함수 호출이 완료됐을 때 `counter`가 이미 증가했으므로 큰 의미가 없다.

https://golang.org/pkg/runtime/#Gosched
위 링크와 번역하신 본문의 맥락을 참고했을 때, 여러 개의 고루틴이 counter를 가지고 경합을 할 때 원자적 연산을 설명하는 것으로 보입니다.  그래서 위와 같이 제안 드립니다

2020-12-26 00:43 UTC, 979156 requested changes

2020-12-26 00:43 UTC, 979156 commented on 128-139/128-139.md
> +우리는 항상 공유 데이터로 4-8바이트의 메모리를 사용하지 않는다. 이곳이 뮤텍스가 들어오는 곳이다. 뮤텍스를 사용하면 모든 고루틴이 한번에 하나씩 실행할 수 있는 WaitGroup(Add, Done and Wait)과 같은 API를 사용할 수 있다.
앞에 두문장만 이정도로 바꿔보시는 것은 어떨까 합니다!

일반적으로 데이터 공유를 하기 위해 매번 4-8바이트를 할당할 만큼 메모리가 여유롭지 않다. 이럴 때 뮤텍스를 사용하면 좋다.

2020-12-26 00:43 UTC, 979156 commented on 128-139/128-139.md
> +`mutex`는 코드의 임계영역을 정의하는데 사용된다. 모든 고루틴들이 통과해야하는 방으로 `mutex`를 상상해보아라. 그러나 한번에 하나의 고루틴만이 이동할 수 있다. 스케줄러는 누가 들어갈지, 그리고 누가 다음이될지를 정한다. 우리는 스케줄러가 무엇을 할 지 결정할 수 없다. 바라건대, 그것은 공정할 것이다. 한 고루틴이 다른 고루틴들보다 먼저 문에
모든 고루틴들이 통과해야하는 방으로 `mutex`를 상상해보아라.
--> 모든 고루틴들이 통과해야하는 방으로 `mutex`를 상상해보자.
: 너무 명령조 같아서요..ㅋㅋ 읽으면서 약간 혼나는것 같았습니다

2020-12-26 00:43 UTC, 979156 commented on 128-139/128-139.md
> +여기서 핵심은 일단 고루틴이 들어오면 그것이 나와있다는 것을 보고해야한다는 것이다. 모든 고루틴들은 다른 고루틴이 들어오도록 나갈때, 잠금과 해제를 요청한다. 두 개의 다른 함수가 동일한 `mutex`를 사용할 수 있으므로 한번에 하나의 고루틴만 주어진 함수를 실행할 수 있다.
여기서 핵심은 들어오도록 허용된 고루틴이, 나갈 때 보고해야 한다는 것이다.
sync.Mutex의 용례를 보았을 때 Lock()과 Unlock()의 사용형태를 위와 같이 대응하여 묘사하면 어떨까 합니다.

2020-12-26 00:43 UTC, 979156 commented on 128-139/128-139.md
> +`rwMutex`는 코드의 임계영역을 정의하는데 사용된다. 그것은 뮤텍스보다 살짝 느리지만 먼저 정확성을 최적화하고있으므로 지금은 신경쓰지 않는다.
그것은 뮤텍스보다 살짝 느리지만 먼저 정확성을 최적화하고 있으므로 지금은 신경쓰지 않는다.
두 번째 문장 띄어쓰기만 수정 요청드립니다!

2020-12-26 00:43 UTC, 979156 commented on 128-139/128-139.md
> +주어신 시간에 발생하는 읽기 수이다. 여기서 `int64`를 보자마자 아토믹 명령어 사용에 대해 생각해야한다.
조회하는 시간에 시도된 읽기 수를 의미한다.

밑에 흐름을 보았을 때 첫문장을 이렇게 바꾸는 것은 어떨까 합니다!

2020-12-26 00:43 UTC, 979156 commented on 128-139/128-139.md
> +현재 `readCount`를 캡쳐한다. 이 호출 없이 수행할 수 있지만 안전하게 보관해라. 우리는 다른 고루틴이 읽고있지 않는지를 확인하고싶다. 이 코드가 실행될 때 `rc`의 값은 항상 0 이어야한다.
현재 `readCount`를 캡쳐한다. 이 호출 없이 수행할 수 있지만 안전하게 처리하는 것이 좋다. 다른 고루틴이 읽기를 수행하지 않는 것을 보장해야 한다. 이 코드가 실행될 때 `rc`의 값은 항상 0 이어야한다.

역시 약간 혼나는 것 같기도 하고 '우리는~'이 약간 마음에 걸려 위와 같이 제안드립니다.

2020-12-26 00:43 UTC, 979156 commented on 128-139/128-139.md
> +아토믹 함수와 뮤텍스는 우리의 소프트웨어에 대기시간을 만든다. 우리가 오케스트레이션을 조정하려고할 때 대기시간이 좋다. 그러나 Read/Write 뮤텍스를 사용하여 대기시간을 줄일 수 있다면 더 좋다.
아토믹 함수와 뮤텍스는 사용자의 소프트웨어에 대기시간을 만든다. 대기시간은 여러 고루틴 사이에 자원 접근에 대한 조율이 필요할 때 유용하다. Read/Write 뮤텍스는 대기시간을 줄이는 데 유용하다.

좀 명확하도록 의역을 해보았습니다.. 원문상 무엇을 조율하는지 명확하지 않고, However라는 말이 굳이 필요한가 싶어서요

2020-12-26 00:43 UTC, 979156 commented on 128-139/128-139.md
> +뮤텍스를 사용하는 경우 가능한 빨리 뮤텍스가 들어오고 나가는지를 확인해라. 추가 작업을 하지마라. 때로는 공유 자원을 로컬 변수로 읽는 것만으로도 충분하다. 뮤텍스에서 수행할 수 있는 작업은 적을수록 좋다. 그런 다음 대기시간을 최소한으로 줄인다.
뮤텍스를 사용하는 경우, 잠금 이후 최대한 빨리 잠금을 해제해야 한다. 다른 불필요한 행위는 하지 않는 것이 좋다. 때로는 공유 자원을 읽기를 위해 로컬 변수만 사용하는 것으로도 충분하다. 뮤텍스를 적게 사용할수록 좋다. 이를 통해 대기시간을 최소한으로 줄일 수 있다.

요런것은 어떨까 합니다..

2020-12-26 00:45 UTC, 979156 commented
@baewang 제가 처음에 실수로 리뷰 2개를 안 묶고 별도로 작성했습니다 ㅜㅜ 감안해서 부탁 드리겠습니다!

2021-01-03 16:17 UTC, davinnovation reviewed
사소한 수정사안 리뷰 드립니다 :)

2021-01-03 16:17 UTC, davinnovation commented on 128-139/128-139.md
> +한번에 오직 하나의 고루틴만이 임계영역에 들어올 수 있도록 허용된다. 이렇게 중괄호를 만들어주면 가독성이 높아진다. 이 작업을 꼭 할필요는 없지만 적극적으로 권장한다. 잠금과 해제 함수는 항상 같은 맥락에 있도록 해야한다.
```suggestion
한번에 오직 하나의 고루틴만이 임계 구역에 접근할 수  있도록 허용된다. 이렇게 중괄호를 만들어주면 가독성이 높아진다. 이 작업을 꼭 할 필요는 없지만 적극적으로 권장한다. 잠금과 해제 함수는 항상 같은 맥락에 있도록 해야한다.
```
임계영역 -> '임계 구역'
-> 변경은 어떨까요? 위키나, 책들에서 임계 구역 혹은 크리티컬 섹션으로 표기하네요.

'이 작업을 꼭 할필요는 없지만 적극적으로 권장한다' -> '이 작업을 꼭 할 필요는 없지만 적극적으로 권장한다.'
-> Typo

2021-01-03 16:17 UTC, davinnovation commented on 128-139/128-139.md
> +많은 고루틴이 읽기를 원하는 공유 자원이 있는 경우가 있다.
```suggestion
많은 고루틴들이 읽기 원하는 공유 자원이 있다고 하자.
```

정도로 의역하면 어떨까요?

2021-01-03 16:17 UTC, davinnovation commented on 128-139/128-139.md
> +때때로, 하나의 고루틴이 들어와서 리소스를 바꿀 수 있다. 그렇게 되면, 모두 읽는 것을 중단해야한다. 아무런 이유없이 소프트웨어에 대기시간을 추가하기 때문에 이러한 유형의 사나리오에서 읽기를 동기화하는 것은 의미가 없다.
```suggestion
때때로, 하나의 고루틴이 들어와서 리소스를 바꿀 수 있다. 그렇게 되면, 모두 읽는 것을 중단해야한다. 아무런 이유 없이 소프트웨어에 대기시간을 추가하기 때문에 이러한 유형의 사나리오에서 읽기를 동기화하는 것은 의미가 없다.
```
typo

2021-01-12 08:44 UTC, baewang commented
@davinnovation @979156 두 분이 의견 주신 내용 반영하였습니다 확인부탁드립니다 :)

2021-01-14 23:37 UTC, 979156 commented
@baewang 님 CI fail만 확인해주시면 바로 merge 하겠습니다. 수고 너무 많으셨습니다!

2021-01-15 07:12 UTC, baewang commented
@979156  왜 안되나 좀 헤맸습니다ㅠㅠ 해결이 된것 같습니다 확인 부탁드립니다 :)

2021-01-16 06:14 UTC, 979156 approved these changes
확인했습니다. 감사합니다!

2021-01-25 23:44 UTC, merged